# Generated by Django 5.0.3 on 2024-03-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['title'], name='Tasks_title_d8e09d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['description'], name='Tasks_descrip_bad359_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='Tasks_created_451077_idx'),
        ),
    ]
